"use client";

import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import {
  DIET_OPTIONS,
  ALLERGEN_OPTIONS,
  HIDDEN_INGREDIENTS,
  USEFUL_PHRASES,
  TAIWAN_VEG_LABELS,
  type DietType,
  type Allergen,
} from "@/constants/diet-phrases";

export function DietCardGenerator() {
  const [selectedDiet, setSelectedDiet] = useState<DietType | null>(null);
  const [selectedAllergens, setSelectedAllergens] = useState<Allergen[]>([]);
  const [showCard, setShowCard] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const dietOption = DIET_OPTIONS.find((d) => d.value === selectedDiet);
  const allergenOptions = ALLERGEN_OPTIONS.filter((a) =>
    selectedAllergens.includes(a.value)
  );

  function toggleAllergen(allergen: Allergen) {
    setSelectedAllergens((prev) =>
      prev.includes(allergen)
        ? prev.filter((a) => a !== allergen)
        : [...prev, allergen]
    );
  }

  function generateCard() {
    if (selectedDiet) setShowCard(true);
  }

  function resetCard() {
    setShowCard(false);
    setSelectedDiet(null);
    setSelectedAllergens([]);
  }

  if (showCard && dietOption) {
    return (
      <div className="space-y-6">
        {/* The Card */}
        <div
          ref={cardRef}
          className="bg-white border-2 border-green-600 rounded-2xl p-6 max-w-lg mx-auto shadow-lg"
        >
          {/* Header */}
          <div className="text-center mb-4 pb-4 border-b border-green-200">
            <h2 className="text-2xl font-bold text-green-700">
              {dietOption.label_zh}
            </h2>
            <p className="text-sm text-gray-500 mt-1">
              {dietOption.label_en}
            </p>
          </div>

          {/* Main Message in Chinese */}
          <div className="bg-green-50 rounded-xl p-4 mb-4">
            <p className="text-lg text-gray-900 leading-relaxed font-medium">
              {dietOption.card_text_zh}
            </p>
            <p className="text-sm text-gray-500 mt-2 italic">
              {dietOption.card_text_en}
            </p>
          </div>

          {/* Allergens */}
          {allergenOptions.length > 0 && (
            <div className="bg-red-50 rounded-xl p-4 mb-4">
              <p className="font-bold text-red-700 mb-2">
                過敏 / Allergies:
              </p>
              {allergenOptions.map((a) => (
                <p key={a.value} className="text-gray-900 mb-1">
                  {a.card_text_zh}
                </p>
              ))}
            </div>
          )}

          {/* Avoid List */}
          <div className="mb-4">
            <p className="font-bold text-gray-700 mb-2">
              請不要加 / Please avoid:
            </p>
            <div className="flex flex-wrap gap-2">
              {dietOption.avoid_zh.map((item, i) => (
                <span
                  key={i}
                  className="bg-red-100 text-red-800 px-3 py-1 rounded-full text-sm font-medium"
                >
                  {item} / {dietOption.avoid_en[i]}
                </span>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="text-center pt-3 border-t border-green-200">
            <p className="text-lg font-bold text-green-700">謝謝！Thank you!</p>
            <p className="text-xs text-gray-400 mt-1">
              Generated by VegMap — vegmap-nu.vercel.app
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-center gap-3">
          <Button variant="outline" onClick={resetCard}>
            Make New Card
          </Button>
        </div>

        {/* Hidden Ingredients Warning */}
        <div className="max-w-lg mx-auto">
          <h3 className="text-lg font-bold mb-3">
            Common Hidden Animal Ingredients in Taiwan
          </h3>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
            <div className="space-y-2">
              {HIDDEN_INGREDIENTS.map((item) => (
                <div key={item.zh} className="flex items-start gap-2">
                  <span className="font-mono text-amber-800 font-bold min-w-[60px]">
                    {item.zh}
                  </span>
                  <span className="text-gray-700">
                    {item.en} — {item.description}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Useful Phrases */}
        <div className="max-w-lg mx-auto">
          <h3 className="text-lg font-bold mb-3">Useful Phrases</h3>
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
            <div className="space-y-2">
              {USEFUL_PHRASES.map((phrase) => (
                <div key={phrase.zh} className="flex items-start gap-3">
                  <span className="font-bold text-blue-900 min-w-[180px]">
                    {phrase.zh}
                  </span>
                  <span className="text-gray-600">{phrase.en}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Selection form
  return (
    <div className="space-y-8 max-w-2xl mx-auto">
      {/* Step 1: Diet Type */}
      <div>
        <h2 className="text-xl font-bold mb-4">1. Select Your Diet Type</h2>
        <div className="grid gap-3">
          {DIET_OPTIONS.map((diet) => (
            <button
              key={diet.value}
              onClick={() => setSelectedDiet(diet.value)}
              className={`text-left p-4 rounded-xl border-2 transition-all ${
                selectedDiet === diet.value
                  ? "border-green-600 bg-green-50"
                  : "border-gray-200 hover:border-green-300"
              }`}
            >
              <div className="flex justify-between items-start">
                <div>
                  <p className="font-bold text-gray-900">{diet.label_en}</p>
                  <p className="text-lg text-green-700 font-medium">
                    {diet.label_zh}
                  </p>
                  <p className="text-sm text-gray-500 mt-1">
                    {diet.description_en}
                  </p>
                </div>
                {selectedDiet === diet.value && (
                  <span className="text-green-600 text-xl">&#10003;</span>
                )}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Step 2: Allergens */}
      <div>
        <h2 className="text-xl font-bold mb-4">
          2. Any Allergies? (Optional)
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {ALLERGEN_OPTIONS.map((allergen) => (
            <button
              key={allergen.value}
              onClick={() => toggleAllergen(allergen.value)}
              className={`p-3 rounded-xl border-2 transition-all text-center ${
                selectedAllergens.includes(allergen.value)
                  ? "border-red-500 bg-red-50"
                  : "border-gray-200 hover:border-red-300"
              }`}
            >
              <p className="font-medium text-gray-900">{allergen.label_en}</p>
              <p className="text-sm text-gray-500">{allergen.label_zh}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Generate Button */}
      <Button
        size="lg"
        className="w-full"
        disabled={!selectedDiet}
        onClick={generateCard}
      >
        Generate My Diet Card
      </Button>

      {/* Taiwan Veg Labels Guide */}
      <div>
        <h2 className="text-xl font-bold mb-4">
          Understanding Taiwan Vegetarian Labels
        </h2>
        <p className="text-gray-600 mb-4">
          Taiwan has a government-mandated 5-category vegetarian labeling system.
          This is different from Western veganism — learning these labels will
          help you identify safe food.
        </p>
        <div className="space-y-3">
          {TAIWAN_VEG_LABELS.map((label) => (
            <div
              key={label.label_zh}
              className="p-4 rounded-xl border border-gray-200"
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xl">{label.icon}</span>
                <span className="font-bold text-green-700">
                  {label.label_zh}
                </span>
                <span className="text-gray-500">({label.label_en})</span>
              </div>
              <p className="text-sm text-gray-700">{label.description}</p>
              {label.warning && (
                <p className="text-sm text-amber-700 mt-1 bg-amber-50 rounded px-2 py-1">
                  Note: {label.warning}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
